package com.dfbz.bugSystem.po;

import com.alibaba.fastjson.JSONObject;

import java.io.Serializable;

public class Module implements Serializable {

    private Integer moduleId;


    private String moduleName;


    private String registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_module.REGISTER_DATE
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    private String registerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_module.UPDATE_ID
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_module.UPDATE_DATE
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    private String updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_module.MODULE_ID
     *
     * @return the value of wp_module.MODULE_ID
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_module.MODULE_ID
     *
     * @param moduleId the value for wp_module.MODULE_ID
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_module.MODULE_NAME
     *
     * @return the value of wp_module.MODULE_NAME
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_module.MODULE_NAME
     *
     * @param moduleName the value for wp_module.MODULE_NAME
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_module.REGISTER_ID
     *
     * @return the value of wp_module.REGISTER_ID
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public String getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_module.REGISTER_ID
     *
     * @param registerId the value for wp_module.REGISTER_ID
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public void setRegisterId(String registerId) {
        this.registerId = registerId == null ? null : registerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_module.REGISTER_DATE
     *
     * @return the value of wp_module.REGISTER_DATE
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public String getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_module.REGISTER_DATE
     *
     * @param registerDate the value for wp_module.REGISTER_DATE
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public void setRegisterDate(String registerDate) {
        this.registerDate = registerDate == null ? null : registerDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_module.UPDATE_ID
     *
     * @return the value of wp_module.UPDATE_ID
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_module.UPDATE_ID
     *
     * @param updateId the value for wp_module.UPDATE_ID
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_module.UPDATE_DATE
     *
     * @return the value of wp_module.UPDATE_DATE
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_module.UPDATE_DATE
     *
     * @param updateDate the value for wp_module.UPDATE_DATE
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }


    @Override
    public String toString() {
        return JSONObject.toJSONString(this);
    }
}