package com.dfbz.bugSystem.dao;

import com.dfbz.bugSystem.po.Module;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface ModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_module
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    @Delete({
        "delete from wp_module",
        "where MODULE_ID = #{moduleId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_module
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    @Insert({
        "insert into wp_module (MODULE_ID, MODULE_NAME, ",
        "REGISTER_ID, REGISTER_DATE, ",
        "UPDATE_ID, UPDATE_DATE)",
        "values (#{moduleId,jdbcType=INTEGER}, #{moduleName,jdbcType=VARCHAR}, ",
        "#{registerId,jdbcType=VARCHAR}, #{registerDate,jdbcType=VARCHAR}, ",
        "#{updateId,jdbcType=VARCHAR}, #{updateDate,jdbcType=VARCHAR})"
    })
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_module
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    @Select({
        "select",
        "MODULE_ID, MODULE_NAME, REGISTER_ID, REGISTER_DATE, UPDATE_ID, UPDATE_DATE",
        "from wp_module",
        "where MODULE_ID = #{moduleId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="MODULE_ID", property="moduleId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="MODULE_NAME", property="moduleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="REGISTER_ID", property="registerId", jdbcType=JdbcType.VARCHAR),
        @Result(column="REGISTER_DATE", property="registerDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_ID", property="updateId", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.VARCHAR)
    })
    Module selectByPrimaryKey(Integer moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_module
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    @Select({
        "select",
        "MODULE_ID, MODULE_NAME, REGISTER_ID, REGISTER_DATE, UPDATE_ID, UPDATE_DATE",
        "from wp_module"
    })
    @Results({
        @Result(column="MODULE_ID", property="moduleId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="MODULE_NAME", property="moduleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="REGISTER_ID", property="registerId", jdbcType=JdbcType.VARCHAR),
        @Result(column="REGISTER_DATE", property="registerDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_ID", property="updateId", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.VARCHAR)
    })
    List<Module> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_module
     *
     * @mbg.generated Wed Sep 02 14:49:00 CST 2020
     */
    @Update({
        "update wp_module",
        "set MODULE_NAME = #{moduleName,jdbcType=VARCHAR},",
          "REGISTER_ID = #{registerId,jdbcType=VARCHAR},",
          "REGISTER_DATE = #{registerDate,jdbcType=VARCHAR},",
          "UPDATE_ID = #{updateId,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=VARCHAR}",
        "where MODULE_ID = #{moduleId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Module record);
}