server:
  port: 9000
spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8716/eureka/
zuul:
  routes:
    user:
      path: /bug/user/**
      url: http://127.0.0.1:8800/